### ISSUE TITLE
ImportError: cannot import name 'sd2_clip' from 'comfy' (unknown location)

### ISSUE THREAD

**Issue by K-O-N-B** [ExponentialML/ComfyUI_Native_DynamiCrafter#29]
help......

Traceback (most recent call last):
  File "H:\ComfyUI-qiuye\ComfyUI\nodes.py", line 1982, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "H:\ComfyUI-qiuye\ComfyUI\custom_nodes\ComfyUI_ModelScopeT2V\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "H:\ComfyUI-qiuye\ComfyUI\custom_nodes\ComfyUI_ModelScopeT2V\nodes.py", line 10, in <module>
    from .configs.modelscope_config import MODELSCOPE_UNET_CONFIG, SD15_CONFIG
  File "H:\ComfyUI-qiuye\ComfyUI\custom_nodes\ComfyUI_ModelScopeT2V\configs\modelscope_config.py", line 6, in <module>
    from comfy import sd2_clip
ImportError: cannot import name 'sd2_clip' from 'comfy' (unknown location)

Cannot import H:\ComfyUI-qiuye\ComfyUI\custom_nodes\ComfyUI_ModelScopeT2V module for custom nodes: cannot import name 'sd2_clip' from 'comfy' (unknown location)
Traceback (most recent call last):
  File "H:\ComfyUI-qiuye\ComfyUI\nodes.py", line 1982, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "H:\ComfyUI-qiuye\ComfyUI\custom_nodes\ComfyUI_Native_DynamiCrafter\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "H:\ComfyUI-qiuye\ComfyUI\custom_nodes\ComfyUI_Native_DynamiCrafter\nodes.py", line 11, in <module>
    from .utils.model_utils import DynamiCrafterBase, DYNAMICRAFTER_CONFIG, \
  File "H:\ComfyUI-qiuye\ComfyUI\custom_nodes\ComfyUI_Native_DynamiCrafter\utils\model_utils.py", line 9, in <module>
    from comfy import sd2_clip
ImportError: cannot import name 'sd2_clip' from 'comfy' (unknown location)

**Comment by ranchen3010** [comment]
I also found this problem, has it been solved?

**Comment by K-O-N-B** [comment]
> I also found this problem, has it been solved?

no...

**Comment by richardyip** [comment]
Plus+1, same question.

**Comment by lepiai** [comment]
comfyui_native_dynamicrafter/utils/model_utils.py
```
# from comfy import sd2_clip
from comfy.text_encoders import sd2_clip
```

After modifying the import method, although it can be imported correctly, there will still be other issues that have been confirmed to be caused by Comfyui upgrade，so...

**Comment by jelling** [comment]
Workaround is to create symbolic link to the new path:

```
/workspace/ComfyUI/comfy# ln -s text_encoders/sd2_clip.py sd2_clip.py
```
